### ISSUE TITLE
Multiple covariates

### ISSUE THREAD

**Issue by mldoucette1** [skranz/xsynthdid#1]
Thanks for this package. Could you provide an example/code for the use of multiple covariates? I am unable to include more than one "x" using the adjust.outcome.for.x function. Below: the first example works fine but I cant figure out the correct language to include more than one "x"

<img width="642" alt="Screen Shot 2022-01-17 at 3 52 01 PM" src="https://user-images.githubusercontent.com/97917533/149835717-797e1964-a3bc-43a0-9b8e-8cc4ed00eef5.png">

**Comment by skranz** [comment]
Your `x` argument should be a vector. Can you try whether it works when specifying it as follows:

```
x = c("unemployment_rate","rpcpi")
```

**Comment by mldoucette1** [comment]
Thanks, much appreciated!
