### ISSUE TITLE
xsdid_se_bootstrap does not properly read column index parameters

### ISSUE THREAD

**Issue by iProdigy** [skranz/xsynthdid#2]
When calling `xsdid_se_bootstrap`, if I pass the integer indices for unit/time/outcome/treatment/x, I get the following error (which disappears if I use the column names in string form): 
```
Error in feols(form, data = xpanel): The left hand side must be a numeric matrix (or vector). Problem: it is of length 0, while
it should have a positive length.
```

**Comment by skranz** [comment]
Thanks for the info. Integer column indices were indeed not yet correctly handled by `xsdid_se_bootstrap`. (I always used column names when testing that function, which was added after the first version of the package). I now pushed a commit onto Github that solves the issue in my tests. Could you check whether then everything works fine in you application? (May take a while until r-universe has compiled the new version, though).

**Comment by iProdigy** [comment]
Passing either column names or integer indices works now! Thank you ❤️
