### ISSUE TITLE
Standardization/Scaling sensitivity

### ISSUE THREAD

**Issue by emilmirzayev** [skranz/xsynthdid#3]
Greetings Sebastian,

thanks for this package! I found it by chance when looking through issues on original R implementation.

Have you considered to have checks on sensitivity of your approach to scale of covariates? Does one need to scale or at least standardize/demean?

thanks,
Emil

**Comment by skranz** [comment]
Hi Emil,

I haven't thought about this point and wasn't aware that this could be an issue. If yes, do you have a concrete example (ideally with simulated data) where things go wrong without appropriate scaling first when using xsynthdid?

**Comment by emilmirzayev** [comment]
Hi,

I also did not think about it before. Yet, after seeing [this issue](https://github.com/synth-inference/synthdid/issues/71) on `synthdid` I had a hunch that it might be worth considering.
My use case also includes units which might have quite different characteristics on some dimensions. For that reason, this is quite an interesting question to me as well

**Comment by skranz** [comment]
I adapted the example from [this issue](https://github.com/synth-inference/synthdid/issues/71). For the xsynthdid approach, scaling does not seem to be an issue:




```r
library(xsynthdid)


data('california_prop99')

set.seed(1)
dat <- as_tibble(california_prop99) %>%
  mutate(
    y = PacksPerCapita,
    x1 = runif(n()), x2 = runif(n())
  ) %>%
  as.data.frame()

dat$y.adj = adjust.outcome.for.x(dat,unit="State",time = "Year",
  outcome = "y",treatment = "treated", x=c("x1","x2"))

pm = panel.matrices(
    dat,unit = "State",time = "Year",
    outcome = "y", treatment = "treated"
  )
sdid1 = synthdid_estimate(Y=pm$Y,N0=pm$N0,T0 = pm$T0)
sdid1
```

```
## synthdid: -15.604 +- NA. Effective N0/N0 = 16.4/38~0.4. Effective T0/T0 = 2.8/19~0.1. N1,T1 = 1,12.
```

```r
# Different scaling
dat$x1 = dat$x1 *1000
dat$y.adj = adjust.outcome.for.x(dat,unit="State",time = "Year",
  outcome = "y",treatment = "treated", x=c("x1","x2"))

pm = panel.matrices(
    dat,unit = "State",time = "Year",
    outcome = "y", treatment = "treated"
  )
sdid2 = synthdid_estimate(Y=pm$Y,N0=pm$N0,T0 = pm$T0)
sdid2
```

```
## synthdid: -15.604 +- NA. Effective N0/N0 = 16.4/38~0.4. Effective T0/T0 = 2.8/19~0.1. N1,T1 = 1,12.
```

```r
# -> Scaling has no effect on result
```

**Comment by emilmirzayev** [comment]
thank you for swift replies! 
This indeed answers my question. It would be beneficial to have this info on README as well if it does not require lot of effort. 
Also, maybe add some info how to cite your work? Bib example in README would be beneficial as well.

**Comment by skranz** [comment]
Thanks for the suggestion. It is probably best to cite the package vignette as:

Kranz, Sebastian (2021), "Synthetic Difference-in-Differences with Time-Varying Covariates", mimeo 

(I added it to the README.md). I have not yet explicitly mentioned that scaling is no issue, but will add it if more people also wonder about that.
